server:
  port: 8080
  servlet:
    context-path: /be-santander-stock-quote-recreation

spring:
  datasource:
    drive-class-name: org.postgresql.Driver
    url: postgres://dcmpzfsglxyhzz:c9de85cb4772458b0a3cc203f00d633818df3a7d11eb388a80f35a0a8e8656e0@ec2-35-170-21-76.compute-1.amazonaws.com:5432/db4k2r0jtrsvdo
    username: dcmpzfsglxyhzz
    password: c9de85cb4772458b0a3cc203f00d633818df3a7d11eb388a80f35a0a8e8656e0
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Project made for the DIO - Santander Bootcamp
